#!/usr/bin/env python3 -u
# Copyright 2024 FBK

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

import argparse
import csv
import pandas as pd


def main(args: argparse.Namespace):
    """
    Replaces the target sentences in the original tsv file with tokenized hypotheses taken from the
    model's output.
    """
    with open(args.model_output, 'r') as f:
        hypos = {}
        for line in f:
            # Gets the tokenized hypotheses and hypotheses number
            if line.startswith('H'):
               splits = line.split('\t')
               line_id = int(splits[0].split('-', 1)[1])
               hypos[line_id] = splits[2].strip()

    # Order hypotheses based on their number
    ordered_tgt_text = [hypos[i] for i in range(len(hypos))]

    df = pd.read_csv(args.original_tsv, sep='\t')
    df['tgt_text'] = ordered_tgt_text
    df.to_csv(args.explain_tsv, sep='\t', index=False, quoting=csv.QUOTE_NONE, escapechar='\\')


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description='Prepares a preprocessed tsv file for explanation generation where the '
                    'reference target sentences are replaced with BPE-tokenized hypotheses '
                    'generated by a fairseq model.')
    
    parser.add_argument('--model-output', type=str, required=True,
                        help='Path to a text file containing the hypotheses generated by a '
                             'fairseq model.')

    parser.add_argument('--original-tsv', type=str, required=True,
                        help='Path to the original tsv containing the preprocessed data.')
    
    parser.add_argument('--explain-tsv', type=str, required=True,
                        help='Path to the new tsv file for generating explanations.')
    
    parsed_args = parser.parse_args()
    main(parsed_args)
